### ISSUE TITLE
ODataBatch swallowed exception details

### ISSUE THREAD

**Issue by mwchan** [object/Simple.OData.Client#148] opened 2015-09-03 03:31 UTC
Hi,

When performing a batch insert and getting a BadRequest exception, I can see the exception details from Fiddler. But when batch.ExecuteAsync() returns the exception, the inner error is missing.

In fiddler:
--batchresponse_5a665d5c-9563-43f5-8739-370fc1e293fd
Content-Type: multipart/mixed; boundary=changesetresponse_1db8fa6f-122c-412b-8e0d-2c1d88f055f9

--changesetresponse_1db8fa6f-122c-412b-8e0d-2c1d88f055f9
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

HTTP/1.1 400 Bad Request
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
OData-Version: 4.0

{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Here is the stack trace that I am interested which appears in Fiddler"
    }
  }
}
--changesetresponse_1db8fa6f-122c-412b-8e0d-2c1d88f055f9--
--batchresponse_5a665d5c-9563-43f5-8739-370fc1e293fd--

From visual studio, I get a WebRequestException with the following properties:

Code: BadRequest
InnerException: null
Message: BadRequest
Stacktrace:    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Simple.OData.Client.ODataClient.<ExecuteBatchAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
.....

Thanks!

**Comment by mwchan** [comment] 2015-09-03 03:51
The same thing happens for an error 500 Internal Server Error.

HTTP/1.1 500 Internal Server Error
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
OData-Version: 4.0

**Comment by mwchan** [comment] 2015-09-03 06:16
Sorry, I forgot to mention that inserting through a batch returns an exception with a null Reponse. If the insertion is done without using a batch, the error is actually contained in the Reponse attribute of the WebRequestException.

**Comment by mwchan** [comment] 2015-09-08 08:51
I am not sure if this will help but I was wondering if it could be because batch request returns a 200 code and then a 400 code in the change set.

![image](https://cloud.githubusercontent.com/assets/13030742/9730513/984fe6c8-5649-11e5-910b-70492e7fe55e.png)

**Comment by object** [comment] 2015-09-09 09:36
Thanks for detailed information. I will investigate this thoroghly.

**Comment by mwchan** [comment] 2015-09-25 09:38
Hi,

I am just wondering if this has been fixed in 4.11 cause I am still experiencing the same issue.

Thanks!

**Comment by object** [comment] 2015-11-19 21:30
The issue is fixed and will be released in version 4.13 (in a few days from now).

**Comment by mwchan** [comment] 2015-11-20 01:43
Cheers!

**Comment by object** [comment] 2015-11-20 14:48
Fixed in 4.13.

**Closed by object** 2015-11-20 14:48 UTC
Labels: bug
