### ISSUE TITLE
Simple.OData.Client 4.23.4 does not work with Microsoft.OData 7.0.0

### ISSUE THREAD

**Issue by HEBOS** [object/Simple.OData.Client#298] opened 2016-08-25 08:21 UTC
**If we use Microsoft.OData 7.0.0. instead of 6.15, and we run our app V4 adapter cannot be loaded.**

**Here is the exception we get:**
{System.InvalidOperationException: Unable to load OData adapter from assembly Simple.OData.Client.V4.Adapter ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'Microsoft.OData.Core.ODataMessageReaderSettings' from assembly 'Microsoft.OData.Core, Version=6.15.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  at (wrapper managed-to-native) System.Reflection.MonoCMethod:InternalInvoke (System.Reflection.MonoCMethod,object,object[],System.Exception&)  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00002] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:644   --- End of inner exception stack trace ---  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00016] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:650   at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00089] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:635   at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:663   at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:62   at Simple.OData.Client.AdapterFactory.LoadAdapter (System.String adapterAssemblyName, System.String adapterTypeName, System.Object[] ctorParams) [0x0004b] in <filename unknown>:0   --- End of inner exception stack trace ---  at Simple.OData.Client.AdapterFactory.LoadAdapter (System.String adapterAssemblyName, System.String adapterTypeName, System.Object[] ctorParams) [0x00083] in <filename unknown>:0   at Simple.OData.Client.AdapterFactory+<>c__DisplayClass13.<GetAdapterLoader>b__12 () [0x00000] in <filename unknown>:0   at Simple.OData.Client.AdapterFactory+<CreateAdapterAsync>d__0.MoveNext () [0x000c4] in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535   at Simple.OData.Client.Session+<ResolveAdapterAsync>d__b.MoveNext () [0x001ff] in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535   at Simple.OData.Client.ODataClient+<FindEntriesAsync>d__ba.MoveNext () [0x000b1] in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535   at Simple.OData.Client.FluentClientBase`1+<RectifyColumnSelectionAsync>d__4[T].MoveNext () [0x0009d] in <filename unknown>:0 --- End of stack trace from previous location where exception was thrown ---  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/external/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357   at Orderion.App.ViewModels.HomeViewModel+<GetShops>d__20.MoveNext () [0x002a2] in U:\OrderionSolution\Orderion.App\Orderion.App\ViewModels\HomeViewModel.cs:85 }
"  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00016] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:650 \n  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00089] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:635 \n  at System.Reflection.MonoCMethod.Invoke (BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:663 \n  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in /Users/builder/data/lanes/3540/1cf254db/source/mono/mcs/class/corlib/System.Reflection/ConstructorInfo.cs:62 \n  at Simple.OData.Client.AdapterFactory.LoadAdapter (System.String adapterAssemblyName, System.String adapterTypeName, System.Object[] ctorParams) [0x0004b] in <filename unknown>:0 "

**Comment by object** [comment] 2016-08-25 09:32
ODataLib 7.0 is not supported yet. They discontinued some PCL profiles so I will have to check if this is a breaking change and I will need to increase major version of Simple.OData.Client to use it with ODataLib 7.

**Comment by Allann** [comment] 2016-08-25 13:59
I had a quick look and moving to v7 would be a major undertaking and WILL need to include breaking changes.  If help is needed just let me know.

**Comment by HEBOS** [comment] 2016-08-25 14:03
Thanks,

 

OK, I'll stick to previous version for now.

Are you planning to support v7 in the near future?

 

 

Hrvoje Matić, mag. inf.

E:  <mailto:ibicom@ibicom.hr> ibicom@ibicom.hr

T: +385 (0)1 6182-501

M: +385 (0)91 201-9678

**Comment by object** [comment] 2016-08-25 14:25
Definitely for the forthcoming version 5.0. Not sure about current V4. Don't want to introduce huge change without buming up a version.

**Comment by object** [comment] 2016-08-25 16:36
Thanks Allan, if you have time to look more into what needs to be done, you are very welcome!

**Comment by Allann** [comment] 2016-08-26 12:28
Do you want me to use a particular solution or create a new one with just the v4 stuff in it as OData v7 drops support for earlier versions?  I cloned the repository and tried Client.All.sln and whilst it builds it has failing tests.  This will make it more difficult to ensure any changes I make do not break the code.

**Comment by object** [comment] 2016-08-26 18:31
Ideally it would be great to use current solution (start with Client.Win and later do Client.All) but I am doing some major changes to tests removing dependencies on Microsoft SQL Server CE so all tests will be run in-memory). I don't plan supporting ODataLib 7 in Client Version 4 since they removed profile 259 - the one client is using. So it will be next major version of the library.

**Comment by NetTecture** [comment] 2016-10-13 10:11
Is there some sort of time plan for the next major version? Trying to coordinate on my end.

**Comment by object** [comment] 2016-10-19 19:10
Unfortunately I can't give you any time estimate at the moment. Very busy with other projects and until it comes to a completion phase I won't be able to dedicate much time on this one.

**Comment by NetTecture** [comment] 2017-01-07 16:24
Seeing tons of stuff updated. Any update on a timeframe?

**Comment by object** [comment] 2017-01-07 16:50
Can't really give a time estimate. I am not even sure now if the next major version of Simple.OData.Client (V5) should support ODataLib 7.0. The problem is that currently Simple.OData.Client combines support for OData protocol versions 1-3 and 4, covered by two different Microsoft libraries. With ODataLib 7 Microsoft  in addition to many breaking changes chose a new PCL profile making it impossible to combine with ODataLib for OData 1-3. Apparently there are no plans for updating ODataLib 1-3, so if I want to support ODataLib 7 I should discontinue support for ODataLib 1-3 in newer versions, and it requires major structural revision of the whole my library.

I have an experimental branch odatalib7 with lots of test failures (that's considerable amount of work on its own), but since this is not just a major upgrade but an important decision of the future of Simple.OData.Client, I can't come up with time estimate on when all this will be sorted out.

**Comment by NetTecture** [comment] 2017-04-21 15:00
@object Any news on this? It is now late April 2017 and I am pulling around old versions in some portals just because of simple odata client, while the server components are happily updated. It starts getting to a non funny point - sadly you do not offer a paid license (I would pay), but I am now on a point that I consider replacing this with another library simple because there is no outlook at the moment.

**Comment by object** [comment] 2017-04-22 20:41
I am sorry to disappoint you, but I can hardly find time for a major upgrade these days. I am fully loaded with other projects at the moment and my biggest problem is that none of my current project uses OData, so I maintain this library only when I have some spare time. To make the matter worse, Microsoft is giving me hard time with the way they handle ODataLib. Until ODataLib V7 came out, their both versions of ODataLib for OData V1-3 and OData V4 were built using the same PCL profile. ODataLib V7 changed the profile, and will probably change it again for .NET Standard. On the top of it is a pile of breaking changes, so I no longer know wether Simple.OData.Client V5 should drop support for OData V1-3 and jump straight to ODataLib V7 or stay with ODataLib V6 for the sake of supporing OData V1-3. So lots of decisions, plenty of failing tests with OData V7 and lack of free time.
So without support from other devs I don't think I will manage major version upgraded in the nearest future. I know this is not the answer you would like to hear.

**Comment by NetTecture** [comment] 2017-04-28 09:30
@object  Well, if you ask me drop all the legacy - it is not like MS is still working on them. After all, even if you make a v5, v4 is still around. Sort of sad, but at the end not work the effort. Sadly, and bigger, is the missing support for current versions by now. I am slowly phasing out simple odata client - not so much because of that, but because of architectural changes (generated management odata for powershell, web apps directly talking to the server is the next step), but for where I still want it - I really am stuck now for extended periods using an outdated library in parts of my product. I would pay for support or a license - but no way and no product. Damn.
No, not what I wanted to hear, but then - you fight battles with the army you have, not the one you want to have ;) At least I know now that I can not count on an update to hit me within let's say 3 months - so I can implement workarounds. Thanks.

**Comment by object** [comment] 2017-04-28 11:22
Fair enough. And when it comes to me, none of my project have been dependent on OData protocol for at least the last couple of years. Which makes it still OK to maintain whatever is already released fixing bugs and adding small features, but it's not easy to come with big design changes if you are not actively using the library yourself. I am open for others to join the library development because juding from package download count, the library is actively used so it deserves to be continued.

**Comment by NetTecture** [comment] 2017-04-28 11:45
I agree. You should commercialize it ;) But then, few people may pay - so not worth it either. Right now there sadly is no really usable OData library - yours is getting outdated, the standard functioality from MS is not working in VS 2017 with OData 4. Rock and hard place, I love being between. Well, not. What did you move on? I move from WCF to OData, and where structures are simple (no web usage) and performance critical - Protobuf.

**Comment by object** [comment] 2017-04-28 14:33
I guess my move is more radical: currently writing a system in F# using Akka.NET. Quite far from OData :-)

**Comment by object** [comment] 2017-10-26 14:44
For your information: I just pushed the version 5.0.0-beta2 that supports .NET Standard 2.0 and updated to use ODataLib7.

**Closed by object** 2017-10-26 14:44 UTC
Labels: implemented, nextmajor

**Comment by NetTecture** [comment] 2017-10-26 14:45
AMAZING, Thanks. I am currently keeping this particular project on hold until mid November for a rework to .NET standard 2 - this is VERY welcome and with amazing timing ;)
