### ISSUE TITLE
Meaningless error on insert

### ISSUE THREAD

**Issue by junker76** [object/Simple.OData.Client#73] opened 2015-01-20 10:43 UTC
We have a very strange behaviour we are currently investigating.
At very randon times, while issuing 
Await client.For(entitySetName).Set(entity).InsertEntryAsync(False)
we receive the following error:
   System.AggregateException: At least one error has occurred. ---> System.Threading.Tasks.TaskCanceledException: A task has been canceled.
that does not have any detail of the reason of the fail.

We have a data sync utility that uploads to a remote server some data; there are several Insert operations done one in sequence (ie: 1000) but often the failure raises at early stage.

Is there any way to obtain some extra details?
Thank you.

**Comment by object** [comment] 2015-01-21 06:52
Hi,

Thank you for the report. This is very strange indeed. Never experienced such error.

One way to obtain extra details is to trace HTTP communication so you can check the whole payload of the failed command and commands prior to the failure. Fiddler is a popular choice for such monitoring, can you try it?

**Comment by junker76** [comment] 2015-01-21 07:35
We know fiddler and employed it as often as possible. In addition, we enabled trace on server side. The problem is that the issue is very random and we don't know how to replicate it. Further complicating, the issue raised only in production environment (where fiddler cannot be installed due to customer IT policies). Server tracing aside, our only option is to enforse error catching and hndling on client side.

The client application is a LightSwitch-Silverlight application, interacting with the synchronization componente via COM - this 'mess' of tecnologies probably inject some kind of problems that are not catched very well in the managed stack.

**Comment by object** [comment] 2015-01-21 08:37
But you don't need to run Fiddler on a server - it should be run on the client machine when your LightSwitch-SL app runs. Still don't have such possibility?
I can build a debug version of S.O.C. that traces all HTTP requests and responses. Would it help?

**Comment by junker76** [comment] 2015-01-21 10:28
Thank you for your response.
Sorry but it seems that I was not clear:
 - regarding the server, we activated asp.net tracing (we know fiddler is not necessary on the server side)
 - regarding the client: we cannot install fiddler due to IT restrictions (users have no sufficient priviligies to install new software)

Having the debug version you are mentioning could be very usefull.
Thank you.

**Comment by object** [comment] 2015-01-21 12:14
I see. You can do the following.

First, enable tracing of Simple.OData.Client. It has OnTrace property, set it similar to this:

OnTrace = (x, y) => Console.WriteLine(string.Format(x, y));

Replace Console.WriteLine with something else to write to the file. This will ensure all requests URI are logged.

But this won't probably be sufficient because you also want to inspect all request and response payloads. In Release mode this is not done for the sake of performance. So get from this repository latest "master" branch, build Debug version of Simple.OData.Client, replace with it the DLL that your app is using and try again. Then you should get a log with all HTTP request/response payload data. Hopefully it will help you inspect the problem. Let me know how it goes.

**Comment by junker76** [comment] 2015-01-21 13:46
Thank you very much

**Comment by object** [comment] 2015-04-23 12:12
Unable to reproduce.

**Comment by Allann** [comment] 2015-08-18 09:45
Funny thing happened to me today...  i am able to reproduce this consistently now.

I believe it is due to the ReuseHttpConnection setting in ODataClientSettings.  This is false by default and when 2 async tasks (using the same client) call GetHttpClient in session, the existing httpClient is disposed, and therefore cancels the task before creating a new client to run the 2nd request.

This call to GetHttpClient does not have any exception handling and therefore bubbles the exception up to the calling code on the client.

**Comment by object** [comment] 2015-08-18 13:01
That's a good one, thanks :+1:

**Comment by object** [comment] 2015-08-20 12:56
Fixed in 4.10.

**Closed by object** 2015-08-20 12:56 UTC

**Comment by junker76** [comment] 2015-09-04 07:06
It seems to solve our problem.
Thank you very much!
