### ISSUE TITLE
ODataJsonLightPropertyAndValueDeserializer_ReadPropertyValue Error On Complex Return Types

### ISSUE THREAD

**Issue by AlexaHLE** [object/Simple.OData.Client#478] opened 2018-05-29 17:46 UTC
I'm not sure If this is an issue with how Simple.OData.Client calls it, or Microsoft.OData.Core itself, but after updating past 4.29.0 I get the following error any time I call an action that returns a ComplexType:

> Microsoft.OData.ODataException
  HResult=0x80131509
  Message=An internal error 'ODataJsonLightPropertyAndValueDeserializer_ReadPropertyValue' occurred.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.JsonLight.ODataJsonLightPropertyAndValueDeserializer.ReadNonEntityValueImplementation(String payloadTypeName, IEdmTypeReference expectedTypeReference, PropertyAndAnnotationCollector propertyAndAnnotationCollector, CollectionWithoutExpectedTypeValidator collectionValidator, Boolean validateNullValue, Boolean isTopLevelPropertyValue, Boolean insideComplexValue, String propertyName, Nullable`1 isDynamicProperty)

I'm able to call the actions successfully through other methods such as postman, and I can see from adding logging to OnTrace in my ODataClient that the method is returning 200, it just can't parse the resulting object.

It doesn't seem to matter what the properties of the ComplexType are, even an object with no properties returns this error. If I Configure them on the API side to instead to be EntityTypes or downgrade Simple.OData.Client back to 4.29.0 they can be called without error.

**Comment by object** [comment] 2018-05-29 18:28
Can you send me the result from Postman and your service Metadata document?

**Comment by AlexaHLE** [comment] 2018-05-29 19:53
Postman:

![image](https://user-images.githubusercontent.com/15944304/40681808-668ebaca-6347-11e8-9a44-5332b28a3cd0.png)

Metadata:
```<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
        <Schema Namespace="ApiActionExample.Model" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <ComplexType Name="ExampleComplex">
                <Property Name="SomeProperty" Type="Edm.String" />
                <Property Name="SomeOtherProperty" Type="Edm.Int32" Nullable="false" />
            </ComplexType>
            <EntityType Name="ExampleEntity">
                <Key>
                    <PropertyRef Name="ID" />
                </Key>
                <Property Name="ID" Type="Edm.Int32" Nullable="false" />
                <Property Name="SomeProperty" Type="Edm.String" />
            </EntityType>
        </Schema>
        <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
            <Action Name="ExampleAction" IsBound="true">
                <Parameter Name="bindingParameter" Type="Collection(ApiActionExample.Model.ExampleEntity)" />
                <ReturnType Type="ApiActionExample.Model.ExampleComplex" />
            </Action>
            <EntityContainer Name="Container">
                <EntitySet Name="ExampleEntity" EntityType="ApiActionExample.Model.ExampleEntity" />
            </EntityContainer>
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>```

**Comment by object** [comment] 2018-05-29 20:01
Thanks. I suppose you are using .NET FX, not .NET Core. If it's NET Core, then it may be fixed in 5.1.

**Comment by AlexaHLE** [comment] 2018-05-29 20:12
Yes I'm using .Net FX

**Comment by object** [comment] 2018-05-30 14:56
@AlexaHLE I managed to reproduce the error. It was caused by changes in Microsoft.OData.Core V7. Fix will be released in 5.2.0.

**Closed** 2018-05-31 05:35 UTC
Labels: bug, implemented

**Comment by AlexaHLE** [comment] 2018-06-04 16:21
@object Thank you for fixing this so quickly. Do you have a timeline for when 5.2.0 will be available in NuGet?

**Comment by object** [comment] 2018-06-04 20:17
It's released now.

**Comment by andrewcot** [comment] 2018-06-07 21:40
Hello! I'm working on the same project and we have run into a secondary issue after this fix was applied (we are now at version 5.2.1), We have found that the ODataClient is returning values in an unexpected way. For example, we have a call made using the client as follows:

`IDictionary<string, object> response = await client.For("ExampleEntity").Key(key).Action("ExampleAction").ExecuteAsSingleAsync();`

Previously this would return a dictionary with keys for the properties like this:
`SomeProperty : test`
`SomeOtherProperty : 1`

However after the update, the dictionary instead contains a key called "__result" and contains all the OData information as the value:
`__result : {"@odata.context" : "http://localhost/App/$metadata#ApiActionExample.Model.ExampleComplex", "SomeProperty" : "test", "SomeOtherProperty" : "1"}`

I've found that if I pull out the value and desrialize it, everything does work like before, but it seems like the __result shouldn't be returned by the client, it should already be unwrapped when it returns from the Execute method.

We have also tried using the `For<ExampleComplex>` overload that returns the object rather than a dictionary. While this does return the object, none of the properties are set.

All of our javascript calls to the OData methods work correctly, it is only when using the ODataClient object on the server side that we experience any problems.

**Comment by object** [comment] 2018-06-08 00:52
@andrewcot The best would be if you open another issue so it will be easier to track it. Paste there what you wrote here plus the following:
- What version broke the correct behavior? You have this problem in 5.2.1. What was the last version when it worked for you?
- Is the metadata document the same that @AlexaHLE  sent earlier?
- What was the OData response from the server when this OData action was called?

**Comment by andrewcot** [comment] 2018-06-08 01:58
Opened issue 486 as requested

**Comment by object** [comment] 2018-06-08 11:16
Thanks!
