### ISSUE TITLE
4.21.0 Odata v3 can't filter by DateTime

### ISSUE THREAD

**Issue by scastria** [object/Simple.OData.Client#275] opened 2016-07-15 20:40 UTC
I just upgraded to 4.21.0 of the Simple.Odata.V3.Client and now my filters by DateTime do not work.  The say, "type is not supported when converting to a uri literal"

**Comment by object** [comment] 2016-07-16 11:31
This is very strange because the only thing that's changed in 4.21 is a single line related to execution of OData functions, nothing that might have to do with date parsing.

What was the last version that worked for you? Can you send me a code sample and your service metadata?

**Comment by scastria** [comment] 2016-08-03 18:13
Sorry for the delay.  4.20 was the last working version for me.  My code sample is:

`				DateTime beforeDT = dateRange[0];
				DateTime afterDT = dateRange[1];
				sdpResults = (await client.For<sumDailyProduction>().Filter(x => (x.docDate >= beforeDT) && (x.docDate < afterDT) && (x.EntityType == (int)EntityType.ProductionPoint)).FindEntriesAsync()).ToList();`

The EntityType used in the code sample is just an enum that I am casting to int for the filter criteria.

I will send you the metadata in a private message.

**Comment by scastria** [comment] 2016-08-03 19:40
I did some debugging against your source code checking each commit from 4.20 until now to see which commit broke my code.  It turns out to be this commit:

https://github.com/object/Simple.OData.Client/commit/1af0a7e843b689a7feb34f14b08617c35d92918f

In debugging, I can see that before this commit, the value being passed into:

`ODataUriUtils.ConvertToUriLiteral(x, odataVersion, (_session.Adapter as ODataAdapter).Model)`

to be converted is the simple DateTime objects from my Linq expression. In other words, it gets called 3 times, once to convert the first DateTime, a second to convert the second DateTime, and a third to convert the EntityType.ProductionPoint which is just a number 4.  However, after this commit, this conversion function is being called just once with some weird async anonymous object that contains both DateTimes objects inside.  See the attached screenshot of my debugger.  Hopefully, this helps you.

![screen shot 2016-08-03 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/4534494/17379471/4598d19a-5988-11e6-84aa-efaf5ecd092f.png)

**Comment by object** [comment] 2016-08-04 07:27
Thanks, this is definitely helpful.

**Comment by vgregor** [comment] 2016-09-01 08:40
This bug is also present in  Simple.OData.V4.Client version="4.23.4". After filtering data with date parameters we get an error:"The type 'System.DateTime' is not supported when converting to a URI literal." 

BTW
Thanks for your work.

**Comment by scastria** [comment] 2016-12-07 15:36
What is the status on this one?  I find it hard to find out what fixes/features go into each NuGet version.  I see 4.24.0.1 now.  Is this fix in there?

**Comment by scastria** [comment] 2017-01-20 17:45
FYI: This is still broken in 4.25.3.

**Comment by scastria** [comment] 2017-02-27 17:29
What is the status on this one?  Can I pay someone to fix this one for me?

**Comment by object** [comment] 2017-02-28 05:42
Hi,
No need to pay, let me check this out later today.

**Comment by object** [comment] 2017-02-28 20:40
@scastria, I checked the code and indeed there was a conversion failure but strangely only in V4 adapter (as @vgregor noted), and you opened the issue for the V3. Are you sure you are still experiencing the same error when using V3 adapter and not V4?

And ODataUriUtils.ConvertToUriLiteral is called 3 times when I test.

**Comment by object** [comment] 2017-02-28 20:51
BTW I just pushed version 4.25.5. that fixes DateTime issue for V4 adapter, but I don't manage to reproduce the failure for V3 adapter.

**Comment by scastria** [comment] 2017-03-02 17:03
Yes, it is still happening with V3 adapter.  Is there anyway you can make the same fix you did for V4 even though you can't reproduce it.  I can test it for you.

**Comment by object** [comment] 2017-03-02 19:38
The same fix wouldn't do - V4 doesn't support DateTime, only DateTimeOffset, therefore I had to add a conversion between those types. V3 supports both. Here's the code that I changed and the test that first failed for V4, now it works for both:

https://github.com/object/Simple.OData.Client/commit/71dcafbd750b5864669ac62568f669c8434e544a

Are you using Visual Studio? I am puzzled what's different in our environments. Is it possible for you to extract a small app that would reproduce the error? Since the error happens on the client side, you don't need the app to connect to the actual OData service - just point ODataClientSettings to your metadata xml, it should fail before going over the wire.

**Comment by scastria** [comment] 2017-03-03 22:17
I am using Xamarin.iOS and Xamarin.Android in a mobile app and can recreate it.  I have attached a sample program that demonstrates this for both iOS and Android.  Since Xamarin is now free and open source, hopefully you won't have a problem recreating this on Android inside Visual Studio.  Everything works fine if you revert Simple.OData.Client back to 4.20.0.  NOTE:  Since I have not included proper login credentials in the sample program, "everything works fine" means you get an Unauthorized exception instead of the URI literal exception.

[TestOData.zip](https://github.com/object/Simple.OData.Client/files/818057/TestOData.zip)
Here is the stack trace I get when running this sample program:

`[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Microsoft.Data.OData.ODataException: The type 'TestODataDroid.MainActivity+<OnCreate>c__async0+<OnCreate>c__AnonStorey1' is not supported when converting to a URI literal.
[MonoDroid]   at Microsoft.Data.OData.Evaluation.LiteralFormatter.FormatRawLiteral (System.Object value) [0x0015c] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Evaluation.LiteralFormatter.FormatAndEscapeLiteral (System.Object value) [0x00000] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Evaluation.LiteralFormatter+DefaultLiteralFormatter.FormatLiteralWithTypePrefix (System.Object value) [0x00000] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Evaluation.LiteralFormatter+DefaultLiteralFormatter.Format (System.Object value) [0x0000d] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Query.ODataUriConversionUtils.ConvertToUriPrimitiveLiteral (System.Object value, Microsoft.Data.OData.ODataVersion version) [0x0001e] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Query.ODataUriUtils.ConvertToUriLiteral (System.Object value, Microsoft.Data.OData.ODataVersion version, Microsoft.Data.Edm.IEdmModel model, Microsoft.Data.OData.ODataFormat format) [0x0004d] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Microsoft.Data.OData.Query.ODataUriUtils.ConvertToUriLiteral (System.Object value, Microsoft.Data.OData.ODataVersion version, Microsoft.Data.Edm.IEdmModel model) [0x00008] in <64ef04a0b78a455b97f017f5e27d932d>:0 
[MonoDroid]   at Simple.OData.Client.V3.Adapter.CommandFormatter+<>c__DisplayClass1.<ConvertValueToUriLiteral>b__0 (System.Object x) [0x00021] in <9b7cfbd7f2684e19a38450e0e93af5d6>:0 
[MonoDroid]   at Simple.OData.Client.V3.Adapter.CommandFormatter.ConvertValueToUriLiteral (System.Object value, System.Boolean escapeDataString) [0x0007f] in <9b7cfbd7f2684e19a38450e0e93af5d6>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.FormatValue (Simple.OData.Client.ExpressionContext context) [0x00080] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.Format (Simple.OData.Client.ExpressionContext context) [0x00022] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.FormatExpression (Simple.OData.Client.ODataExpression expr, Simple.OData.Client.ExpressionContext context) [0x0000f] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.Format (Simple.OData.Client.ExpressionContext context) [0x0015f] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.FormatExpression (Simple.OData.Client.ODataExpression expr, Simple.OData.Client.ExpressionContext context) [0x0000f] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.ODataExpression.Format (Simple.OData.Client.ExpressionContext context) [0x00127] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.FluentCommand.Resolve () [0x000ef] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid]   at Simple.OData.Client.FluentCommand+<GetCommandTextAsync>d__0.MoveNext () [0x0009d] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
[MonoDroid]   at Simple.OData.Client.ODataClient+<FindEntriesAsync>d__ba.MoveNext () [0x00147] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
[MonoDroid]   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:535 
[MonoDroid]   at Simple.OData.Client.FluentClientBase`1+<RectifyColumnSelectionAsync>d__4[T].MoveNext () [0x0009d] in <b0fcad0c3e0448faaf69892ba181c3d2>:0 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
[MonoDroid]   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:357 
[MonoDroid]   at TestODataDroid.MainActivity+<OnCreate>c__async0.MoveNext () [0x001e5] in /Users/shawncastrianni/Projects/TestOData/TestODataDroid/MainActivity.cs:34 
[MonoDroid] --- End of stack trace from previous location where exception was thrown ---
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
[MonoDroid]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 
[MonoDroid]   at Android.App.SyncContext+<Post>c__AnonStorey0.<>m__0 () [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:18 
[MonoDroid]   at Java.Lang.Thread+RunnableImplementor.Run () [0x0000b] in /Users/builder/data/lanes/3511/501e63ce/source/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
[MonoDroid]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3511/501e63ce/source/monodroid/src/Mono.Android/platforms/android-24/src/generated/Java.Lang.IRunnable.cs:81 
[MonoDroid]   at (wrapper dynamic-method) System.Object:04ad1aba-6201-4aaf-a43c-30a60591f788 (intptr,intptr)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
[Mono] DllImport searching in: '__Internal' ('(null)').
[Mono] Searching for 'java_interop_jnienv_throw'.
[Mono] Probing 'java_interop_jnienv_throw'.
[Mono] Found as 'java_interop_jnienv_throw'.
[mono] 
[mono] Unhandled Exception:
[mono] Microsoft.Data.OData.ODataException: The type 'TestODataDroid.MainActivity+<OnCreate>c__async0+<OnCreate>c__AnonStorey1' is not supported when converting to a URI literal.
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Data.OData.ODataException: The type 'TestODataDroid.MainActivity+<OnCreate>c__async0+<OnCreate>c__AnonStorey1' is not supported when converting to a URI literal.
`

**Comment by object** [comment] 2017-03-05 07:23
Thank you, I will try it in your environment.

**Comment by scastria** [comment] 2017-04-19 18:21
Any luck on this one?

**Comment by object** [comment] 2017-04-23 08:27
Well, you will be surprised but I believe I've found what's the problem. Took time because I didn't have proper environment to test but your test project and observation that it started happening after 4.20 helped a lot. I've located where things work differently and it is deep inside reflection code. I am figuring out how to fix it in a best way but expect a new version today :-)

**Comment by object** [comment] 2017-04-23 12:41
I believe it's fixed now. Will be released shortly as 4.26. Sorry for long resolution process. and thanks for your patience and test projects (that helped massively).

**Closed** 2017-04-23 14:22 UTC
Labels: bug, implemented
